name: Build

on:
  workflow_dispatch: {}
  push:
    branches: [ "main" ]
    tags:
      - v**
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set test variable
      id: set-variable
      run: |
        if [ ${{ github.ref }} == 'refs/heads/main' ]; then
          echo "RELEASE_VERSION=latest" >> $GITHUB_ENV
        elif [ ${{ github.ref }} == 'refs/tags/*' ]; then
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        else
          echo "IMAGE_TAG=dev" >> $GITHUB_ENV
        fi
      shell: bash

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Login to GitHub Container Registry
      if: env.IMAGE_TAG != 'dev'
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

#     - name: Build
#       run: make docker-build
#       env:
#         IMG: ghcr.io/topicuskeyhub/keyhub-vault-operator:latest

#     - name: Push to GitHub Container Registry
#       if: startsWith(github.ref, 'refs/heads/main') || startsWith(github.ref, 'refs/heads/release/')
#       run: make docker-push
#       env:
#         IMG: ghcr.io/topicuskeyhub/keyhub-vault-operator:latest
