name: Renovate

on:
  - workflow_dispatch

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: renovatebot/github-action@v32.37.2
        with:
          configurationFile: .github/renovate-config.js
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          LOG_LEVEL: 'debug'
